--- 
pipeline: 
  build: 
    commands: 
      - yarn
    image: "node:alpine"
  notify: 
    channel: drone
    image: plugins/slack
    secrets: 
      - slack_webhook
    webhook: <slack_webhook>
  pre-release: 
    commands: 
      - "yarn build"
      - "tar -zcvf build.tar.gz -C build ."
    image: "node:alpine"
    when: 
      event: tag
  release: 
    api_key: <github_token>
    files: 
      - build.tar.gz
    image: plugins/github_release
    secrets: 
      - github_token
    when: 
      event: tag
  test: 
    commands: 
      - "yarn test"
    image: "node:alpine"